### PR TITLE
Captain's suit resprite

### PR DESCRIPTION
**Pull request by Hyenh**
## About the PR

Replaces the Captain's hardsuit sprite.
## Why / Balance

Requested.
## Technical details

Changes sprite, desc and name.
## Media

image

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

no cl

### CODE REVIEW

**Comment by Just-a-Unity-Dev** [comment]
Please move to a unique texture under _FTL/ (just copy and paste the RSI and path to the _FTL folder, and revert the old commit)

**Comment by Hyenh** [comment]
> Please move to a unique texture under _FTL/ (just copy and paste the RSI and path to the _FTL folder, and revert the old commit)

Should I do the same for the merc hardsuit

**Comment by Just-a-Unity-Dev** [comment]
Yeah

**Review by Just-a-Unity-Dev — CHANGES_REQUESTED** [review]
Refer to above comment

**Pull request merged**
