### PR TITLE
A ton of ship updates

### PR DESCRIPTION
**Pull request by Blackern5000**
I present to you
(probably) functioning Station Administrator job that I don't know how to make an NPC/ghost role spawner for.
SA access card in the spawn room for the trade station command to fix this issue. ^
Faction access doors on every NPC ship (minus a couple specific cases)
NPCs on every NPC ship (who are armed with weapons!!)
A few ships may be missing atmos because nobody ever fixgridatmos-ed them but I'm tired and ready to go to bed and just want to submit this before I do.

### CODE REVIEW

**Comment by Blackern5000** [comment]
me when I accidentally write "JobStationAdministator" instead of "JobStationAdministrator"

**Comment by Blackern5000** [comment]
I genuinely have no idea what this means or how to fix it.

**Comment by Blackern5000** [comment]
the error was fake it was all in my head

**Comment by Blackern5000** [comment]
it was all in github's head*

**Comment by Just-a-Unity-Dev** [comment]
fuck it we blindmerge

**Pull request merged**
