### PR TITLE
The Nesasio

### PR DESCRIPTION
**Pull request by Blackern5000**
"They stole our ship"
"How did they steal our ship"
"They boarded it and shot everyone, then warped away before we could shoot them back."
"Eh it's just one ship, what's the worst they could do?"
What IS the worst you could do?

The Nesasio is a player ship built by the Frontier Stability Corporation with 11 cryo pods, 6 guns, two gun control rooms, a mini armory with c4, no windows at the piloting room, cameras in every room, a door control room, a cool shape, a short backstory, FOUR (MAYBE real???) NUKES, a place to drop said nukes when you're flying over a warzone, and personal bedrooms for the captain and HoS, (CE and CMO simply aren't important enough.)
A more up-to-date alternative to the kestrel and paper-plane, the FSC Nesasio-Class Stealth Bomber is built with the new guns system in mind for a more prolonged and hopefully more action-filled round.

FSC-Nesasio-Class-Stealth-Bomber

### CODE REVIEW

**Comment by Blackern5000** [comment]
what does that error even mean

**Comment by Just-a-Unity-Dev** [comment]
try asking upstream, but this is an issue regarding your map file

**Comment by Blackern5000** [comment]
IT IS LITERALLY THERE WHAT DO YOU MEAN "FILE NOT FOUND"

**Comment by Blackern5000** [comment]
screw you too I'll figure this out when my brain is functioning at full capacity in like 8-10 hours

**Comment by Blackern5000** [comment]
WHAT EVEN WENT WRONG THIS TIME???

**Pull request merged**
